name: johnturpin
favicon: null
layout_spectrum: 0.7944835689850152
typography_spectrum: 0.5404416921082884
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6047260253690183
  lightness: 0.21879115304909647
  saturation: 0.9450196283869445
  rhythmicContrast: 0.17983912047930062
purpose: []
